name: "Plot artifacts size"
description: "This action allows you to draw some plots"
author: kroune

inputs:
  github-token:
    description: "github auth token"
    required: true
  repository-owner:
    description: "name of the repository owner"
    required: true
  repository-name:
    description: "name of the repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: install needed packages
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_REPOSITORY_OWNER: ${{ inputs.repository-owner }}
        INPUT_REPOSITORY_NAME: ${{ inputs.repository-name }}
